version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - app-network

  ollama-container:
    image: ollama/ollama:latest
    pull_policy: always
    tty: true
    restart: always
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
    networks:
      - app-network
    environment:
      - OLLAMA_KEEP_ALIVE=24h

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - qdrant
      - ollama-container
    networks:
      - app-network
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_HOST=ollama-container:11434
      - LOCALHOST=ollama-container

networks:
  app-network:
    driver: bridge



